#ifndef _CHARACTER_ID_H_
#define _CHARACTER_ID_H_

enum CharacterID
{
	CHARACTER_PLAYER,
	CHARACTER_ENEMY,
	CHARACTER_ENEMY_BOSS,
	CHARACTER_PLAYER_BULLET,
	CHARACTER_PLAYER_BOMB,
	CHARACTER_ENEMY_BULLET,
	CHARACTER_ITEM,
	CHARACTER_EFFECT
};

#endif