#ifndef _TEXTURE_ID_H_
#define _TEXTURE_ID_H_

enum TextureID
{
	TEXTURE_BG,
	TEXTURE_PLAYER,
	TEXTURE_ENEMY,
	TEXTURE_ENEMY_BOSS,
	TEXTURE_PLAYER_BULLET,
	TEXTURE_PLAYER_BOMB,
	TEXTURE_ENEMY_BULLET,
	TEXTURE_ITEM,
	TEXTURE_EFFECT,
	TEXTURE_UI,
	TEXTURE_UI_1,
	TEXTURE_UI_2,
	TEXTURE_UI_3,
	TEXTURE_UI_4,
	TEXTURE_EMPTY
};

#endif